version: '3.8'

services:
  telegram-bot:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    container_name: telegram-client
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/telegram_db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - telegram-bot

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: telegram_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata:
